name: 'Pull Request'

on:
  push:
  pull_request:
    types: [opened reopened syncronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v1

      - name: Lint code
        run: npm run lint

      - name: Lint styles
        run: npm run lint:stylelint

      - name: Check formatting
        run: npm run prettier:check
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build-storybook

      - name: Chromatic
        uses: chromaui/action@v1
        with:
          storybookBuildDir: ./storybook-static
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
