name: "Pull Request"

on:
  push:
  pull_request:
    types: [opened reopened syncronize]

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build-storybook

      - name: Chromatic
        uses: chromaui/action@v1
        with:
          storybookBuildDir: ./storybook-static
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}